settings:
  templateDir: "/home/swapnil/.config/leet/templates/"

templates:
  cpp-make:
    folder: "cpp"
    files:
      - "main.cpp"
      - "Makefile"
  python:
    folder: "py"
    files:
      - "main.py"
