settings:
  templateDir: "/home/swapnil/.config/leet/templates/"

templates:
  cpp-make:
    language: C++
    files:
      - "main.cpp"
      - "Makefile"

  python:
    language: Python
    files:
      - "main.py"
